# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrewSysMain.ui'
#
# Created: Fri Jul 29 20:24:04 2016
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_brewSysMain(object):
    def setupUi(self, brewSysMain):
        brewSysMain.setObjectName(_fromUtf8("brewSysMain"))
        brewSysMain.setWindowModality(QtCore.Qt.WindowModal)
        brewSysMain.resize(1024, 516)
        font = QtGui.QFont()
        font.setKerning(True)
        brewSysMain.setFont(font)
        brewSysMain.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        brewSysMain.setMouseTracking(True)
        brewSysMain.setLayoutDirection(QtCore.Qt.RightToLeft)
        brewSysMain.setAutoFillBackground(False)
        self.temperatureFrame = QtGui.QFrame(brewSysMain)
        self.temperatureFrame.setGeometry(QtCore.QRect(20, 10, 591, 131))
        self.temperatureFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.temperatureFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.temperatureFrame.setObjectName(_fromUtf8("temperatureFrame"))
        self.mtInTempDisplay = QtGui.QTextEdit(self.temperatureFrame)
        self.mtInTempDisplay.setGeometry(QtCore.QRect(210, 40, 175, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.mtInTempDisplay.setFont(font)
        self.mtInTempDisplay.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mtInTempDisplay.setAutoFormatting(QtGui.QTextEdit.AutoNone)
        self.mtInTempDisplay.setReadOnly(True)
        self.mtInTempDisplay.setObjectName(_fromUtf8("mtInTempDisplay"))
        self.mtOutTempDisplay = QtGui.QTextEdit(self.temperatureFrame)
        self.mtOutTempDisplay.setGeometry(QtCore.QRect(400, 40, 175, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.mtOutTempDisplay.setFont(font)
        self.mtOutTempDisplay.setReadOnly(True)
        self.mtOutTempDisplay.setObjectName(_fromUtf8("mtOutTempDisplay"))
        self.hltTempDisplay = QtGui.QTextEdit(self.temperatureFrame)
        self.hltTempDisplay.setGeometry(QtCore.QRect(20, 40, 175, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.hltTempDisplay.setFont(font)
        self.hltTempDisplay.setReadOnly(True)
        self.hltTempDisplay.setObjectName(_fromUtf8("hltTempDisplay"))
        self.hltTempLable = QtGui.QLabel(self.temperatureFrame)
        self.hltTempLable.setGeometry(QtCore.QRect(40, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.hltTempLable.setFont(font)
        self.hltTempLable.setAlignment(QtCore.Qt.AlignCenter)
        self.hltTempLable.setObjectName(_fromUtf8("hltTempLable"))
        self.mltTempLable = QtGui.QLabel(self.temperatureFrame)
        self.mltTempLable.setGeometry(QtCore.QRect(400, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mltTempLable.setFont(font)
        self.mltTempLable.setAlignment(QtCore.Qt.AlignCenter)
        self.mltTempLable.setObjectName(_fromUtf8("mltTempLable"))
        self.mltInTempLable = QtGui.QLabel(self.temperatureFrame)
        self.mltInTempLable.setGeometry(QtCore.QRect(210, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mltInTempLable.setFont(font)
        self.mltInTempLable.setAlignment(QtCore.Qt.AlignCenter)
        self.mltInTempLable.setObjectName(_fromUtf8("mltInTempLable"))
        self.hltPumpStatusDisplay = QtGui.QLineEdit(brewSysMain)
        self.hltPumpStatusDisplay.setGeometry(QtCore.QRect(114, 250, 121, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hltPumpStatusDisplay.sizePolicy().hasHeightForWidth())
        self.hltPumpStatusDisplay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hltPumpStatusDisplay.setFont(font)
        self.hltPumpStatusDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.hltPumpStatusDisplay.setObjectName(_fromUtf8("hltPumpStatusDisplay"))
        self.mtPumpStatusDisplay = QtGui.QLineEdit(brewSysMain)
        self.mtPumpStatusDisplay.setGeometry(QtCore.QRect(114, 320, 121, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mtPumpStatusDisplay.sizePolicy().hasHeightForWidth())
        self.mtPumpStatusDisplay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mtPumpStatusDisplay.setFont(font)
        self.mtPumpStatusDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.mtPumpStatusDisplay.setObjectName(_fromUtf8("mtPumpStatusDisplay"))
        self.label_5 = QtGui.QLabel(brewSysMain)
        self.label_5.setGeometry(QtCore.QRect(30, 270, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(brewSysMain)
        self.label_6.setGeometry(QtCore.QRect(30, 340, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.proceedButton = QtGui.QPushButton(brewSysMain)
        self.proceedButton.setGeometry(QtCore.QRect(20, 420, 591, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.proceedButton.setFont(font)
        self.proceedButton.setObjectName(_fromUtf8("proceedButton"))
        self.hltHeaterStatusDisplay = QtGui.QLineEdit(brewSysMain)
        self.hltHeaterStatusDisplay.setGeometry(QtCore.QRect(114, 180, 121, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hltHeaterStatusDisplay.sizePolicy().hasHeightForWidth())
        self.hltHeaterStatusDisplay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hltHeaterStatusDisplay.setFont(font)
        self.hltHeaterStatusDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.hltHeaterStatusDisplay.setObjectName(_fromUtf8("hltHeaterStatusDisplay"))
        self.label_7 = QtGui.QLabel(brewSysMain)
        self.label_7.setGeometry(QtCore.QRect(30, 200, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.timeLeftDisplay = QtGui.QLCDNumber(brewSysMain)
        self.timeLeftDisplay.setEnabled(True)
        self.timeLeftDisplay.setGeometry(QtCore.QRect(340, 170, 161, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.timeLeftDisplay.setFont(font)
        self.timeLeftDisplay.setObjectName(_fromUtf8("timeLeftDisplay"))
        self.label_TimeLeft = QtGui.QLabel(brewSysMain)
        self.label_TimeLeft.setGeometry(QtCore.QRect(340, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_TimeLeft.setFont(font)
        self.label_TimeLeft.setObjectName(_fromUtf8("label_TimeLeft"))
        self.frame = QtGui.QFrame(brewSysMain)
        self.frame.setGeometry(QtCore.QRect(20, 170, 301, 231))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.hltHeaterToggleButton = QtGui.QPushButton(self.frame)
        self.hltHeaterToggleButton.setEnabled(False)
        self.hltHeaterToggleButton.setGeometry(QtCore.QRect(220, 10, 71, 71))
        self.hltHeaterToggleButton.setObjectName(_fromUtf8("hltHeaterToggleButton"))
        self.hltPumpToggleButton = QtGui.QPushButton(self.frame)
        self.hltPumpToggleButton.setEnabled(False)
        self.hltPumpToggleButton.setGeometry(QtCore.QRect(220, 80, 71, 71))
        self.hltPumpToggleButton.setObjectName(_fromUtf8("hltPumpToggleButton"))
        self.mltPumpToggleButton = QtGui.QPushButton(self.frame)
        self.mltPumpToggleButton.setEnabled(False)
        self.mltPumpToggleButton.setGeometry(QtCore.QRect(220, 150, 71, 71))
        self.mltPumpToggleButton.setObjectName(_fromUtf8("mltPumpToggleButton"))
        self.label_TimeLeft_2 = QtGui.QLabel(brewSysMain)
        self.label_TimeLeft_2.setGeometry(QtCore.QRect(20, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_TimeLeft_2.setFont(font)
        self.label_TimeLeft_2.setObjectName(_fromUtf8("label_TimeLeft_2"))
        self.splitter = QtGui.QSplitter(brewSysMain)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pauseSpargeButton = QtGui.QPushButton(brewSysMain)
        self.pauseSpargeButton.setGeometry(QtCore.QRect(340, 300, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pauseSpargeButton.setFont(font)
        self.pauseSpargeButton.setObjectName(_fromUtf8("pauseSpargeButton"))
        self.tabWidget = QtGui.QTabWidget(brewSysMain)
        self.tabWidget.setGeometry(QtCore.QRect(620, 10, 391, 391))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.step1TempSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.step1TempSpinBox.setGeometry(QtCore.QRect(50, 40, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.step1TempSpinBox.setFont(font)
        self.step1TempSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.step1TempSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.step1TempSpinBox.setDecimals(1)
        self.step1TempSpinBox.setMaximum(90.0)
        self.step1TempSpinBox.setSingleStep(0.5)
        self.step1TempSpinBox.setObjectName(_fromUtf8("step1TempSpinBox"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(50, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.step1Indicator = QtGui.QPushButton(self.tab)
        self.step1Indicator.setGeometry(QtCore.QRect(10, 50, 21, 21))
        self.step1Indicator.setFocusPolicy(QtCore.Qt.NoFocus)
        self.step1Indicator.setText(_fromUtf8(""))
        self.step1Indicator.setObjectName(_fromUtf8("step1Indicator"))
        self.step1TimeSpinBox = QtGui.QSpinBox(self.tab)
        self.step1TimeSpinBox.setGeometry(QtCore.QRect(170, 40, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.step1TimeSpinBox.setFont(font)
        self.step1TimeSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.step1TimeSpinBox.setObjectName(_fromUtf8("step1TimeSpinBox"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(170, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(280, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.mashInTempSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.mashInTempSpinBox.setGeometry(QtCore.QRect(280, 40, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mashInTempSpinBox.setFont(font)
        self.mashInTempSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mashInTempSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.mashInTempSpinBox.setDecimals(1)
        self.mashInTempSpinBox.setMaximum(90.0)
        self.mashInTempSpinBox.setSingleStep(0.5)
        self.mashInTempSpinBox.setObjectName(_fromUtf8("mashInTempSpinBox"))
        self.step2TempSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.step2TempSpinBox.setEnabled(False)
        self.step2TempSpinBox.setGeometry(QtCore.QRect(50, 160, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.step2TempSpinBox.setFont(font)
        self.step2TempSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.step2TempSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.step2TempSpinBox.setDecimals(1)
        self.step2TempSpinBox.setMaximum(90.0)
        self.step2TempSpinBox.setSingleStep(0.5)
        self.step2TempSpinBox.setObjectName(_fromUtf8("step2TempSpinBox"))
        self.step2TimeSpinBox = QtGui.QSpinBox(self.tab)
        self.step2TimeSpinBox.setEnabled(False)
        self.step2TimeSpinBox.setGeometry(QtCore.QRect(170, 160, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.step2TimeSpinBox.setFont(font)
        self.step2TimeSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.step2TimeSpinBox.setObjectName(_fromUtf8("step2TimeSpinBox"))
        self.step2Indicator = QtGui.QPushButton(self.tab)
        self.step2Indicator.setGeometry(QtCore.QRect(10, 170, 21, 21))
        self.step2Indicator.setFocusPolicy(QtCore.Qt.NoFocus)
        self.step2Indicator.setText(_fromUtf8(""))
        self.step2Indicator.setObjectName(_fromUtf8("step2Indicator"))
        self.step2EnableCheckBox = QtGui.QCheckBox(self.tab)
        self.step2EnableCheckBox.setGeometry(QtCore.QRect(280, 170, 94, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.step2EnableCheckBox.setFont(font)
        self.step2EnableCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.step2EnableCheckBox.setObjectName(_fromUtf8("step2EnableCheckBox"))
        self.step3EnableCheckBox = QtGui.QCheckBox(self.tab)
        self.step3EnableCheckBox.setGeometry(QtCore.QRect(280, 290, 94, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.step3EnableCheckBox.setFont(font)
        self.step3EnableCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.step3EnableCheckBox.setObjectName(_fromUtf8("step3EnableCheckBox"))
        self.step3Indicator = QtGui.QPushButton(self.tab)
        self.step3Indicator.setGeometry(QtCore.QRect(10, 290, 21, 21))
        self.step3Indicator.setFocusPolicy(QtCore.Qt.NoFocus)
        self.step3Indicator.setText(_fromUtf8(""))
        self.step3Indicator.setObjectName(_fromUtf8("step3Indicator"))
        self.step2Label_1 = QtGui.QLabel(self.tab)
        self.step2Label_1.setEnabled(False)
        self.step2Label_1.setGeometry(QtCore.QRect(50, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.step2Label_1.setFont(font)
        self.step2Label_1.setObjectName(_fromUtf8("step2Label_1"))
        self.step2Label_2 = QtGui.QLabel(self.tab)
        self.step2Label_2.setEnabled(False)
        self.step2Label_2.setGeometry(QtCore.QRect(170, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.step2Label_2.setFont(font)
        self.step2Label_2.setObjectName(_fromUtf8("step2Label_2"))
        self.step3Label_1 = QtGui.QLabel(self.tab)
        self.step3Label_1.setEnabled(False)
        self.step3Label_1.setGeometry(QtCore.QRect(50, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.step3Label_1.setFont(font)
        self.step3Label_1.setObjectName(_fromUtf8("step3Label_1"))
        self.step3TempSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.step3TempSpinBox.setEnabled(False)
        self.step3TempSpinBox.setGeometry(QtCore.QRect(50, 280, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.step3TempSpinBox.setFont(font)
        self.step3TempSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.step3TempSpinBox.setDecimals(1)
        self.step3TempSpinBox.setMaximum(90.0)
        self.step3TempSpinBox.setSingleStep(0.5)
        self.step3TempSpinBox.setObjectName(_fromUtf8("step3TempSpinBox"))
        self.step3Label_2 = QtGui.QLabel(self.tab)
        self.step3Label_2.setEnabled(False)
        self.step3Label_2.setGeometry(QtCore.QRect(170, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.step3Label_2.setFont(font)
        self.step3Label_2.setObjectName(_fromUtf8("step3Label_2"))
        self.step3TimeSpinBox = QtGui.QSpinBox(self.tab)
        self.step3TimeSpinBox.setEnabled(False)
        self.step3TimeSpinBox.setGeometry(QtCore.QRect(170, 280, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.step3TimeSpinBox.setFont(font)
        self.step3TimeSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.step3TimeSpinBox.setObjectName(_fromUtf8("step3TimeSpinBox"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.mashoutTempSpinBox = QtGui.QDoubleSpinBox(self.tab_3)
        self.mashoutTempSpinBox.setGeometry(QtCore.QRect(50, 40, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mashoutTempSpinBox.setFont(font)
        self.mashoutTempSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mashoutTempSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.mashoutTempSpinBox.setDecimals(1)
        self.mashoutTempSpinBox.setMaximum(90.0)
        self.mashoutTempSpinBox.setSingleStep(0.5)
        self.mashoutTempSpinBox.setObjectName(_fromUtf8("mashoutTempSpinBox"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(50, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.mashoutTimeSpinBox = QtGui.QSpinBox(self.tab_3)
        self.mashoutTimeSpinBox.setGeometry(QtCore.QRect(230, 40, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mashoutTimeSpinBox.setFont(font)
        self.mashoutTimeSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mashoutTimeSpinBox.setObjectName(_fromUtf8("mashoutTimeSpinBox"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(230, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.spargeTempSpinBox = QtGui.QDoubleSpinBox(self.tab_3)
        self.spargeTempSpinBox.setGeometry(QtCore.QRect(50, 140, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.spargeTempSpinBox.setFont(font)
        self.spargeTempSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spargeTempSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.spargeTempSpinBox.setDecimals(1)
        self.spargeTempSpinBox.setMaximum(90.0)
        self.spargeTempSpinBox.setSingleStep(0.5)
        self.spargeTempSpinBox.setObjectName(_fromUtf8("spargeTempSpinBox"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(50, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.hltOvertempSpinBox = QtGui.QDoubleSpinBox(self.tab_4)
        self.hltOvertempSpinBox.setGeometry(QtCore.QRect(50, 40, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.hltOvertempSpinBox.setFont(font)
        self.hltOvertempSpinBox.setToolTip(_fromUtf8(""))
        self.hltOvertempSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hltOvertempSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.hltOvertempSpinBox.setDecimals(1)
        self.hltOvertempSpinBox.setMaximum(90.0)
        self.hltOvertempSpinBox.setSingleStep(0.5)
        self.hltOvertempSpinBox.setObjectName(_fromUtf8("hltOvertempSpinBox"))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(50, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.hltMaxOvershootSpinBox = QtGui.QDoubleSpinBox(self.tab_4)
        self.hltMaxOvershootSpinBox.setGeometry(QtCore.QRect(230, 40, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.hltMaxOvershootSpinBox.setFont(font)
        self.hltMaxOvershootSpinBox.setToolTip(_fromUtf8(""))
        self.hltMaxOvershootSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hltMaxOvershootSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.hltMaxOvershootSpinBox.setDecimals(1)
        self.hltMaxOvershootSpinBox.setMaximum(90.0)
        self.hltMaxOvershootSpinBox.setSingleStep(0.5)
        self.hltMaxOvershootSpinBox.setObjectName(_fromUtf8("hltMaxOvershootSpinBox"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(230, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.hltTempCalibSpinBox = QtGui.QDoubleSpinBox(self.tab_4)
        self.hltTempCalibSpinBox.setGeometry(QtCore.QRect(50, 120, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.hltTempCalibSpinBox.setFont(font)
        self.hltTempCalibSpinBox.setToolTip(_fromUtf8(""))
        self.hltTempCalibSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hltTempCalibSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.hltTempCalibSpinBox.setDecimals(1)
        self.hltTempCalibSpinBox.setMaximum(90.0)
        self.hltTempCalibSpinBox.setSingleStep(0.5)
        self.hltTempCalibSpinBox.setObjectName(_fromUtf8("hltTempCalibSpinBox"))
        self.mltInTempCalibSpinBox = QtGui.QDoubleSpinBox(self.tab_4)
        self.mltInTempCalibSpinBox.setGeometry(QtCore.QRect(50, 200, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mltInTempCalibSpinBox.setFont(font)
        self.mltInTempCalibSpinBox.setToolTip(_fromUtf8(""))
        self.mltInTempCalibSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mltInTempCalibSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.mltInTempCalibSpinBox.setDecimals(1)
        self.mltInTempCalibSpinBox.setMaximum(90.0)
        self.mltInTempCalibSpinBox.setSingleStep(0.5)
        self.mltInTempCalibSpinBox.setObjectName(_fromUtf8("mltInTempCalibSpinBox"))
        self.mltTempCalibSpinBox = QtGui.QDoubleSpinBox(self.tab_4)
        self.mltTempCalibSpinBox.setGeometry(QtCore.QRect(50, 280, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mltTempCalibSpinBox.setFont(font)
        self.mltTempCalibSpinBox.setToolTip(_fromUtf8(""))
        self.mltTempCalibSpinBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mltTempCalibSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.mltTempCalibSpinBox.setDecimals(1)
        self.mltTempCalibSpinBox.setMaximum(90.0)
        self.mltTempCalibSpinBox.setSingleStep(0.5)
        self.mltTempCalibSpinBox.setObjectName(_fromUtf8("mltTempCalibSpinBox"))
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(50, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(50, 260, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(50, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.stepMashApplyButton = QtGui.QPushButton(brewSysMain)
        self.stepMashApplyButton.setGeometry(QtCore.QRect(710, 420, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.stepMashApplyButton.setFont(font)
        self.stepMashApplyButton.setObjectName(_fromUtf8("stepMashApplyButton"))

        self.retranslateUi(brewSysMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(brewSysMain)
        brewSysMain.setTabOrder(self.proceedButton, self.hltHeaterStatusDisplay)
        brewSysMain.setTabOrder(self.hltHeaterStatusDisplay, self.hltPumpStatusDisplay)
        brewSysMain.setTabOrder(self.hltPumpStatusDisplay, self.mtOutTempDisplay)
        brewSysMain.setTabOrder(self.mtOutTempDisplay, self.mtPumpStatusDisplay)
        brewSysMain.setTabOrder(self.mtPumpStatusDisplay, self.hltHeaterToggleButton)
        brewSysMain.setTabOrder(self.hltHeaterToggleButton, self.mtInTempDisplay)
        brewSysMain.setTabOrder(self.mtInTempDisplay, self.hltPumpToggleButton)
        brewSysMain.setTabOrder(self.hltPumpToggleButton, self.mltPumpToggleButton)
        brewSysMain.setTabOrder(self.mltPumpToggleButton, self.hltTempDisplay)

    def retranslateUi(self, brewSysMain):
        brewSysMain.setWindowTitle(QtGui.QApplication.translate("brewSysMain", "BrewSys v0.3", None, QtGui.QApplication.UnicodeUTF8))
        self.mtInTempDisplay.setHtml(QtGui.QApplication.translate("brewSysMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:26pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">00.0/00.0</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hltTempDisplay.setHtml(QtGui.QApplication.translate("brewSysMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:26pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hltTempLable.setText(QtGui.QApplication.translate("brewSysMain", "HLT", None, QtGui.QApplication.UnicodeUTF8))
        self.mltTempLable.setText(QtGui.QApplication.translate("brewSysMain", "MLT", None, QtGui.QApplication.UnicodeUTF8))
        self.mltInTempLable.setText(QtGui.QApplication.translate("brewSysMain", "MLT In", None, QtGui.QApplication.UnicodeUTF8))
        self.hltPumpStatusDisplay.setText(QtGui.QApplication.translate("brewSysMain", "Working", None, QtGui.QApplication.UnicodeUTF8))
        self.mtPumpStatusDisplay.setText(QtGui.QApplication.translate("brewSysMain", "Working", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("brewSysMain", "HLT Pump:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("brewSysMain", "MLT Pump:", None, QtGui.QApplication.UnicodeUTF8))
        self.proceedButton.setText(QtGui.QApplication.translate("brewSysMain", "Mashing", None, QtGui.QApplication.UnicodeUTF8))
        self.hltHeaterStatusDisplay.setText(QtGui.QApplication.translate("brewSysMain", "Working", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("brewSysMain", "HLT Heater:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_TimeLeft.setText(QtGui.QApplication.translate("brewSysMain", "Rest Time Remaining", None, QtGui.QApplication.UnicodeUTF8))
        self.hltHeaterToggleButton.setText(QtGui.QApplication.translate("brewSysMain", "Toggle", None, QtGui.QApplication.UnicodeUTF8))
        self.hltPumpToggleButton.setText(QtGui.QApplication.translate("brewSysMain", "Toggle", None, QtGui.QApplication.UnicodeUTF8))
        self.mltPumpToggleButton.setText(QtGui.QApplication.translate("brewSysMain", "Toggle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_TimeLeft_2.setText(QtGui.QApplication.translate("brewSysMain", "System Status", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseSpargeButton.setText(QtGui.QApplication.translate("brewSysMain", "Pause Sparge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("brewSysMain", "Temp Step 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("brewSysMain", "Time Step 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("brewSysMain", "Strike Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.step2EnableCheckBox.setText(QtGui.QApplication.translate("brewSysMain", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.step3EnableCheckBox.setText(QtGui.QApplication.translate("brewSysMain", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.step2Label_1.setText(QtGui.QApplication.translate("brewSysMain", "Temp Step 2", None, QtGui.QApplication.UnicodeUTF8))
        self.step2Label_2.setText(QtGui.QApplication.translate("brewSysMain", "Time Step 2", None, QtGui.QApplication.UnicodeUTF8))
        self.step3Label_1.setText(QtGui.QApplication.translate("brewSysMain", "Temp Step 3", None, QtGui.QApplication.UnicodeUTF8))
        self.step3Label_2.setText(QtGui.QApplication.translate("brewSysMain", "Time Step 3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("brewSysMain", "Step Mash", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("brewSysMain", "Mashout Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("brewSysMain", "Mashout Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("brewSysMain", "Sparge Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("brewSysMain", "Mashout/Sparge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("brewSysMain", "HLT Overtemp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("brewSysMain", "Max HLT Overshoot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("brewSysMain", "HLT Temp Calib.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("brewSysMain", "MLT Temp Calib.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("brewSysMain", "MLT In Temp Calib.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("brewSysMain", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.stepMashApplyButton.setText(QtGui.QApplication.translate("brewSysMain", "Apply/Abort!", None, QtGui.QApplication.UnicodeUTF8))

